apiVersion: v1
kind: ServiceAccount
metadata:
  name: polyscale-argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: polyscale-argocd-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: polyscale-argocd-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polyscale-argocd-role
subjects:
  - kind: ServiceAccount
    name: polyscale-argocd
    namespace: argocd
