groups:
  - name: polyscale
    rules:
      - alert: HighCPUUsage
        expr: avg(rate(container_cpu_usage_seconds_total[5m])) by (pod) > 0.8
        for: 5m
        labels:
          severity: warning
      - alert: HighMemoryUsage
        expr: avg(container_memory_usage_bytes) by (pod) > 700000000
        for: 5m
        labels:
          severity: warning
